package it.polimi.ingsw.litemodel.liteplayer;

public enum Actions {
    USE_MARKET_TRAY,
    PAINT_MARBLE_IN_TRAY,
    BUY_DEV_CARD,
    ACTIVATE_PRODUCTION,
    MOVE_IN_PRODUCTION,
    SET_NORMAL_PRODUCTION,
    MOVE_BETWEEN_DEPOT,
    ACTIVATE_LEADER_CARD,
    DISCARD_LEADER_CARD,
    CHOOSE_RESOURCE,
    END_TURN
}
